language: node_js
node_js:
  - "18"
env:
  global:
    - NODE_OPTIONS=--openssl-legacy-provider
    - CI=false
install:
  - npm install
before_script:
  - chmod +x node_modules/.bin/react-scripts
script:
  - npm run build
